### ISSUE TITLE
Meilisearch (v0.26.0) failed to infer the version of the database. Please consider using a dump to load your data.

### ISSUE THREAD

**Issue by robeng1** [meilisearch/meilisearch-kubernetes#106]
Description
Trying to install on EKS and this error keeps coming up. Its a fresh installation so there's no previous dump.
Meilisearch doesn't start, it just logs the above error. It works when persistence is disabled

Heres what my values.yml looks like 
```
 affinity: {}
 auth: 
   existingMasterKeySecret: meilisearch-master-key
 container: 
   containerPort: 7700
 customLabels: {}
 environment: 
   MEILI_ENV: production
   MEILI_NO_ANALYTICS: true
  fullnameOverride: meilisearch
 image: 
    pullPolicy: IfNotPresent
    pullSecret: ~
    repository: getmeili/meilisearch
    tag: v0.26.0
  ingress: 
    annotations: {}
    enabled: false
    hosts: 
      - meilisearch-example.local
    path: /
    tls: []
  livenessProbe: 
    InitialDelaySeconds: 60
    periodSeconds: 60
  nameOverride: ""
  nodeSelector: {}
  persistence: 
    accessMode: ReadWriteOnce
    annotations: {}
    enabled: true
    size: 100Gi
    storageClass: gp2
    volume: 
      mountPath: /data.ms
      name: data
  podAnnotations: {}
  readinessProbe: 
    InitialDelaySeconds: 60
    periodSeconds: 60
  replicaCount: 1
  resources: {}
  service: 
    annotations: {}
    port: 7700
    type: ClusterIP
  serviceAccount: 
    annotations: {}
```
