### ISSUE TITLE
Extra curly brace in helm chart ingress template

### ISSUE THREAD

**Issue by PykupeJIbc** [meilisearch/meilisearch-kubernetes#142]
**Description**
I tried deploy meilisearch with helm chart, and found mistake in ingress label:

**Expected behavior**
`app.kubernetes.io/managed-by: Helm`

**Current behavior**
`app.kubernetes.io/managed-by: Helm}`

**Screenshots or Logs**
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-meilisearch
  labels:
    helm.sh/chart: meilisearch-0.1.41
    app.kubernetes.io/name: meilisearch
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.29.0"
    app.kubernetes.io/component: search-engine
    app.kubernetes.io/part-of: meilisearch
    app.kubernetes.io/managed-by: Helm}
spec:
  ingressClassName: nginx
  rules:
  - host: "meilisearch-example.local"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: release-name-meilisearch
              port:
                number: 7700
```

**Environment (please complete the following information):**
- meilisearch-kubernetes version: v0.1.41
