### ISSUE TITLE
Pod status is never ready

### ISSUE THREAD

**Issue by fr3fou** [meilisearch/meilisearch-kubernetes#91]
I tried running the Helm Chart with 
```sh
$ helm install meilisearch charts/meilisearch -f values.yaml
```

```yaml
image:
  repository: server_meilisearch
  tag: latest
  pullPolicy: IfNotPresent

# Environment loaded into the configMap
environment:
  MEILI_NO_ANALYTICS: true
  MEILI_ENV: development
  # For production deployment, the environment MEILI_MASTER_KEY is required.
  # If MEILI_ENV is set to "production" without setting MEILI_MASTER_KEY, this
  # chart will automatically create a secure MEILI_MASTER_KEY and push it as a
  # secret. Otherwise the below value of MEILI_MASTER_KEY will be used instead.
  # MEILI_MASTER_KEY:
```
This is the `server_meilisearch` Dockerfile image that was passed into minikube using `minikube image load server_meilisearch`
```dockerfile
FROM ubuntu

WORKDIR /meilisearch

RUN apt-get update
RUN apt-get install -y \
	libc6-dev \
	curl

RUN curl -L https://install.meilisearch.com | sh
RUN chmod +x meilisearch

EXPOSE 7700

CMD ["/bin/sh", "-c", "./meilisearch"]
```
![image](https://user-images.githubusercontent.com/1344906/145694253-dc4b9a54-cfea-4935-a528-35db40dba0bd.png)
This also occurs on other versions of MeiliSearch.
- OS: macOS 11.5.2 on MacBook Pro 2021 M1
- MeiliSearch version: v0.23.1
- meilisearch-kubernetes version: v0.1.21
